Exercise 8
Iabo77/DevOps-Course-Starter pull request #9
Opened 2022-07-19 14:39 UTC by Iabo77

Please make sure you are raising this PR against your own repository and not the original. If it says https://github.com/CorndelWithSoftwire in the search bar right now, you are in the wrong place!

Please also don't forget to submit the PR's url to Aptem afterwards (by clicking on the corresponding exercise component, pasting the url in the textbox that appears and then pressing the finish button).

2022-07-22 15:32 UTC, hugh-emerson requested changes
Nice work, you're so close. You have CD running successfully and I see your app running on Heroku successfully but the trigger for your workflow is not set up correctly. See my comment on your yml file for details.

2022-07-22 15:32 UTC, hugh-emerson commented on .github/workflows/test-push-container-workflow.yml
> +        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
You are implicitly relying on the production stage being the final stage in the Dockerfile. Which an appropriate workaround, since this action doesn't support the `--target` build option, but it's surprising. Developers might adjust the Dockerfile, not expecting the ordering to matter and accidentally break deployments.

Surprising behaviour should be documented. Probably best to leave a comment in the Dockerfile saying that the production stage is deliberately last.

2022-07-22 15:32 UTC, hugh-emerson commented on .github/workflows/test-push-container-workflow.yml
> +      - main
We want to run tests for all branches, not just the main branch.

We want to deploy the app only when the main branch is updated (otherwise the app on Heroku is extremely unstable and corresponds to whatever work in progress was pushed most recently)

What you have configured is:
- Run this workflow for all pull requests
- Also run this workflow whenever the main branch is updated (pushed)

The whole workflow will run, including deployment.

What you need is an `if` condition ([see docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif)) on the `Push-to-Heroku` and `Push-to-Docker` jobs so that they only run on the main branch. And delete this branch condition from here.

2022-08-10 10:25 UTC, JackMead approved these changes
Thanks for making that change, I can see it is now successfully gating your deployments! The syntax for `if` is a bit fiddly so worth checking that it does successfully deploy on the main branch once you merge, but this looks good and I'm happy for you to do so 😄

2022-09-01 12:07 UTC, merged